export const GET_ALL_TASKS_REQUEST = "GET_ALL_TASKS_REQUEST";
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_FAILURE = "GET_ALL_TASKS_FAILURE";
// =========== single task
export const GET_TAST_REQUEST = "GET_TAST_REQUEST";
export const GET_TAST_SUCCESS = "GET_TAST_SUCCESS";
export const GET_TAST_FAILURE = "GET_TAST_FAILURE";
